#!/bin/bash
# Show hyprland keybinds in fuzzel

hyprctl binds -j | jq -r '
  .[]
  | select(.has_description == true and .submap == "")
  | ([
      (if (.modmask / 64 % 2 | floor) == 1 then "Super" else empty end),
      (if (.modmask / 4 % 2 | floor) == 1 then "Ctrl" else empty end),
      (if (.modmask / 8 % 2 | floor) == 1 then "Alt" else empty end),
      (if (.modmask / 1 % 2 | floor) == 1 then "Shift" else empty end)
    ] | join("+")) as $mods
  | (if $mods != "" then $mods + "+" else "" end) + .key + "  " + .description
' | sort | fuzzel --dmenu > /dev/null
