#!/usr/bin/env bash

WEBSITES=(
  "Bluesky"
  "CIBC"
  "Github"
  "Gmail"
  "Messages"
  "Reddit"
  "YouTube"
)

# either arg[1]
if [ -z $1 ]; then
  SELECTED=`printf "%s\n" "${WEBSITES[@]}" | fzf-tmux`
  if [ -z "$SELECTED" ]; then
     printf "See ya\n" && exit 1
  fi
else
  SELECTED=$1
fi

# to lowercase
SELECTED=${SELECTED,,}

case $SELECTED in
    "bluesky")
    WEBSITE=https://bsky.app
    ;;
    "cibc")
    WEBSITE=https://cibc.ca
    ;;
    "github")
    WEBSITE=https://github.com
    ;;
    "gmail")
    WEBSITE=https://mail.google.com
    ;;
    "messages")
    WEBSITE=https://messages.google.com/web/conversations
    ;;
    "reddit")
    WEBSITE=https://reddit.com
    ;;
    "youtube")
    WEBSITE=https://youtube.com
    ;;
esac

chromium --app="$WEBSITE"
